name: 🚀 Deploy website on push

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install --force

      - name: Build app
        run: npm run build

      - name: Deploy to cPanel
        uses: SamKirkland/FTP-Deploy-Action@4.1.0
        with:
          server: ${{ secrets.CPANEL_HOST}}
          username: ${{ secrets.CPANEL_USERNAME}}
          password: ${{ secrets.CPANEL_PASSWORD}}
          server-dir: ./
